spring:
  application:
    name: users
  profiles:
    active: local

---
spring:
  profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    username: root
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none
